CREATE EXTENSION IF NOT EXISTS age;
CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS vector;

SELECT 'CREATE DATABASE langfuse OWNER pulseops'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'langfuse')\gexec
