/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Metrics */
    get: operations["metrics_metrics_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/graph/programs/{program_id}/tree": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Program Tree */
    get: operations["program_tree_graph_programs__program_id__tree_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/webhooks/chat/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Chat Webhook */
    post: operations["chat_webhook_webhooks_chat__provider__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ChatWebhookResponse */
    ChatWebhookResponse: {
      /** Status */
      status: string;
      /** Message Id */
      message_id: string;
    };
    /**
     * EdgeKind
     * @enum {string}
     */
    EdgeKind: "contains" | "assigned_to" | "depends_on";
    /** GraphEdgeDto */
    GraphEdgeDto: {
      /** From Node Id */
      from_node_id: string;
      /** To Node Id */
      to_node_id: string;
      kind: components["schemas"]["EdgeKind"];
      /** Valid From */
      valid_from: string | null;
      /** Valid To */
      valid_to: string | null;
    };
    /** GraphNodeDto */
    GraphNodeDto: {
      /** Id */
      id: string;
      kind: components["schemas"]["NodeKind"];
      /** Name */
      name: string;
      /** Metadata */
      metadata: {
        [key: string]: string | number | boolean | null;
      };
    };
    /** GraphTreeDto */
    GraphTreeDto: {
      root: components["schemas"]["GraphNodeDto"];
      /** Nodes */
      nodes: components["schemas"]["GraphNodeDto"][];
      /** Edges */
      edges: components["schemas"]["GraphEdgeDto"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
      /** Environment */
      environment: string;
      /** Tenant Id */
      tenant_id: string;
      /** Correlation Id */
      correlation_id: string;
    };
    /**
     * NodeKind
     * @enum {string}
     */
    NodeKind: "program" | "project" | "pod" | "developer" | "task";
    /** ReadyResponse */
    ReadyResponse: {
      /** Status */
      status: string;
      /** Dependencies */
      dependencies: {
        [key: string]: boolean;
      };
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  ready_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
    };
  };
  metrics_metrics_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  program_tree_graph_programs__program_id__tree_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GraphTreeDto"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  chat_webhook_webhooks_chat__provider__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatWebhookResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
