/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Metrics */
    get: operations["metrics_metrics_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/graph/programs/{program_id}/tree": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Program Tree */
    get: operations["program_tree_graph_programs__program_id__tree_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/workflows/checkin/dispatch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dispatch Checkin */
    post: operations["dispatch_checkin_admin_workflows_checkin_dispatch_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/workflows/sync/jira": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dispatch Jira Sync */
    post: operations["dispatch_jira_sync_admin_workflows_sync_jira_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/workflows/sync/github": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dispatch Github Sync */
    post: operations["dispatch_github_sync_admin_workflows_sync_github_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/workflows/sync/calendar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dispatch Calendar Sync */
    post: operations["dispatch_calendar_sync_admin_workflows_sync_calendar_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/programs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Config Programs */
    get: operations["list_config_programs_config_programs_get"];
    put?: never;
    /** Create Config Program */
    post: operations["create_config_program_config_programs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/programs/{program_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Config Program */
    get: operations["get_config_program_config_programs__program_id__get"];
    /** Update Config Program */
    put: operations["update_config_program_config_programs__program_id__put"];
    post?: never;
    /** Delete Config Program */
    delete: operations["delete_config_program_config_programs__program_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Config Projects */
    get: operations["list_config_projects_config_projects_get"];
    put?: never;
    /** Create Config Project */
    post: operations["create_config_project_config_projects_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Config Project */
    get: operations["get_config_project_config_projects__project_id__get"];
    /** Update Config Project */
    put: operations["update_config_project_config_projects__project_id__put"];
    post?: never;
    /** Delete Config Project */
    delete: operations["delete_config_project_config_projects__project_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/pods": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Config Pods */
    get: operations["list_config_pods_config_pods_get"];
    put?: never;
    /** Create Config Pod */
    post: operations["create_config_pod_config_pods_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/pods/{pod_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Config Pod */
    get: operations["get_config_pod_config_pods__pod_id__get"];
    /** Update Config Pod */
    put: operations["update_config_pod_config_pods__pod_id__put"];
    post?: never;
    /** Delete Config Pod */
    delete: operations["delete_config_pod_config_pods__pod_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Config Members */
    get: operations["list_config_members_config_members_get"];
    put?: never;
    /** Create Config Member */
    post: operations["create_config_member_config_members_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/directory/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search Config Directory Users */
    get: operations["search_config_directory_users_config_directory_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/directory/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sync Config Directory */
    post: operations["sync_config_directory_config_directory_sync_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/members/from-directory": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Config Members From Directory */
    post: operations["create_config_members_from_directory_config_members_from_directory_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/members/{member_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Config Member */
    get: operations["get_config_member_config_members__member_id__get"];
    /** Update Config Member */
    put: operations["update_config_member_config_members__member_id__put"];
    post?: never;
    /** Delete Config Member */
    delete: operations["delete_config_member_config_members__member_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/projects/{project_id}/program": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Link Config Project Program */
    post: operations["link_config_project_program_config_projects__project_id__program_post"];
    /** Unlink Config Project Program */
    delete: operations["unlink_config_project_program_config_projects__project_id__program_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/pods/{pod_id}/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Link Config Pod Project */
    post: operations["link_config_pod_project_config_pods__pod_id__projects__project_id__post"];
    /** Unlink Config Pod Project */
    delete: operations["unlink_config_pod_project_config_pods__pod_id__projects__project_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/pods/{pod_id}/members/{member_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Link Config Pod Member */
    post: operations["link_config_pod_member_config_pods__pod_id__members__member_id__post"];
    /** Unlink Config Pod Member */
    delete: operations["unlink_config_pod_member_config_pods__pod_id__members__member_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/members/{member_id}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Assign Config Member Task */
    post: operations["assign_config_member_task_config_members__member_id__tasks_post"];
    /** Unassign Config Member Task */
    delete: operations["unassign_config_member_task_config_members__member_id__tasks_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/members/{member_id}/checkin-preference": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Config Member Checkin Preference */
    get: operations["get_config_member_checkin_preference_config_members__member_id__checkin_preference_get"];
    /** Update Config Member Checkin Preference */
    put: operations["update_config_member_checkin_preference_config_members__member_id__checkin_preference_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/config/checkin-preferences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Config Checkin Preferences */
    get: operations["list_config_checkin_preferences_config_checkin_preferences_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/programs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Programs */
    get: operations["list_programs_programs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Projects */
    get: operations["list_projects_projects_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pods": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Pods */
    get: operations["list_pods_pods_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/checkin-preference": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Checkin Preference */
    get: operations["get_checkin_preference_me_checkin_preference_get"];
    /** Update Checkin Preference */
    put: operations["update_checkin_preference_me_checkin_preference_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/focus": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Focus */
    get: operations["my_focus_me_focus_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pods/{pod_id}/blockers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Pod Blockers */
    get: operations["pod_blockers_pods__pod_id__blockers_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pods/{pod_id}/checkins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Pod Checkins */
    get: operations["pod_checkins_pods__pod_id__checkins_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project_id}/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Project Progress */
    get: operations["project_progress_projects__project_id__progress_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/programs/{program_id}/tree": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Program Tree */
    get: operations["program_tree_programs__program_id__tree_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/heatmap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Portfolio Heatmap */
    get: operations["portfolio_heatmap_portfolio_heatmap_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/test/chat-simulator/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chat Simulator Status */
    get: operations["chat_simulator_status_test_chat_simulator_status_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/test/chat-simulator/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Chat Simulator Messages */
    get: operations["chat_simulator_messages_test_chat_simulator_messages_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/test/chat-simulator/messages/{message_id}/reply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Chat Simulator Reply */
    post: operations["chat_simulator_reply_test_chat_simulator_messages__message_id__reply_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/test/chat-simulator/state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Reset Chat Simulator */
    delete: operations["reset_chat_simulator_test_chat_simulator_state_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/webhooks/chat/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Chat Webhook */
    post: operations["chat_webhook_webhooks_chat__provider__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BlockerDto */
    BlockerDto: {
      /** Id */
      id: string;
      /** Description */
      description: string;
      /** Age Days */
      age_days: number;
      /** Owner Id */
      owner_id: string;
      /** Owner Name */
      owner_name: string;
      source: components["schemas"]["StatusSource"];
      /**
       * Status As Of
       * Format: date
       */
      status_as_of: string;
      source_ref: components["schemas"]["EntityRefDto"];
    };
    /** CalendarSyncDispatchRequest */
    CalendarSyncDispatchRequest: {
      /** Tenant Id */
      tenant_id: string;
      /** User Id */
      user_id: string;
      /**
       * Start
       * Format: date
       */
      start: string;
      /**
       * End
       * Format: date
       */
      end: string;
      /** Display Name */
      display_name?: string | null;
      /** Observed At */
      observed_at?: string | null;
    };
    /** ChatSimulatorMessageResponse */
    ChatSimulatorMessageResponse: {
      /** Tenant Id */
      tenant_id: string;
      /** Message Id */
      message_id: string;
      /** Channel Id */
      channel_id: string;
      /** User Id */
      user_id: string;
      /** Direction */
      direction: string;
      /** Text */
      text: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Correlation Id */
      correlation_id?: string | null;
      /** Purpose */
      purpose?: string | null;
      /** Reply To Message Id */
      reply_to_message_id?: string | null;
      /** Metadata */
      metadata: {
        [key: string]: string | number | boolean | null;
      };
    };
    /** ChatSimulatorMessagesResponse */
    ChatSimulatorMessagesResponse: {
      /** Items */
      items: components["schemas"]["ChatSimulatorMessageResponse"][];
    };
    /** ChatSimulatorReplyRequest */
    ChatSimulatorReplyRequest: {
      /** Text */
      text: string;
      /** Received At */
      received_at?: string | null;
    };
    /** ChatSimulatorReplyResponse */
    ChatSimulatorReplyResponse: {
      /** Message Id */
      message_id: string;
      /** Status */
      status: string;
      /** Processed Message Id */
      processed_message_id: string;
    };
    /** ChatSimulatorStatusResponse */
    ChatSimulatorStatusResponse: {
      /** Enabled */
      enabled: boolean;
      /** Tenant Id */
      tenant_id: string;
      /** Provider */
      provider: string;
      /** Message Count */
      message_count: number;
    };
    /** ChatWebhookResponse */
    ChatWebhookResponse: {
      /** Status */
      status: string;
      /** Message Id */
      message_id: string;
    };
    /** CheckinDeveloperDto */
    CheckinDeveloperDto: {
      /** Developer Id */
      developer_id: string;
      /** Developer Name */
      developer_name: string;
      /**
       * State
       * @enum {string}
       */
      state: "confirmed" | "stale" | "missing";
      source: components["schemas"]["StatusSource"];
      /** Status As Of */
      status_as_of: string | null;
      /** Summary */
      summary: string;
    };
    /** CheckinDispatchRequest */
    CheckinDispatchRequest: {
      /** Tenant Id */
      tenant_id: string;
      /** Developer Id */
      developer_id: string;
      /** Developer Name */
      developer_name?: string | null;
      /** Chat External Id */
      chat_external_id?: string | null;
      /** Checkin Date */
      checkin_date?: string | null;
    };
    /** CheckinPreferenceResponse */
    CheckinPreferenceResponse: {
      /** Developer Id */
      developer_id: string;
      /**
       * Local Time
       * Format: time
       */
      local_time: string;
      /** Timezone */
      timezone: string | null;
      /** Weekdays */
      weekdays: number[];
      /** Reply Wait Seconds */
      reply_wait_seconds: number;
      /** Final Reply Wait Seconds */
      final_reply_wait_seconds: number;
    };
    /** CheckinPreferenceUpdateRequest */
    CheckinPreferenceUpdateRequest: {
      /** Local Time */
      local_time?: string | null;
      /** Timezone */
      timezone?: string | null;
      /** Weekdays */
      weekdays?: number[] | null;
      /** Reply Wait Seconds */
      reply_wait_seconds?: number | null;
      /** Final Reply Wait Seconds */
      final_reply_wait_seconds?: number | null;
    };
    /** ConfigEdgeResponse */
    ConfigEdgeResponse: {
      /** From Node Id */
      from_node_id: string;
      /** To Node Id */
      to_node_id: string;
      kind: components["schemas"]["EdgeKind"];
      /** Valid From */
      valid_from: string | null;
      /** Valid To */
      valid_to: string | null;
      /** Metadata */
      metadata: {
        [key: string]: string | number | boolean | null;
      };
    };
    /** ConfigNodeCreateRequest */
    ConfigNodeCreateRequest: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Code */
      code?: string | null;
      /** Metadata */
      metadata?: {
        [key: string]: string | number | boolean | null;
      };
    };
    /** ConfigNodeResponse */
    ConfigNodeResponse: {
      /** Id */
      id: string;
      kind: components["schemas"]["NodeKind"];
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
      /** Code */
      code?: string | null;
      /** Metadata */
      metadata: {
        [key: string]: string | number | boolean | null;
      };
    };
    /** ConfigNodeUpdateRequest */
    ConfigNodeUpdateRequest: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Code */
      code?: string | null;
      /** Metadata */
      metadata?: {
        [key: string]: string | number | boolean | null;
      } | null;
    };
    /** DirectoryItemResponse */
    DirectoryItemResponse: {
      /** Id */
      id: string;
      kind: components["schemas"]["NodeKind"];
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Code */
      code: string | null;
      /** Metadata */
      metadata: {
        [key: string]: string | number | boolean | null;
      };
      rag: components["schemas"]["Rag"] | null;
      source: components["schemas"]["StatusSource"] | null;
      /** Program Ids */
      program_ids: string[];
      /** Project Ids */
      project_ids: string[];
      /** Pod Ids */
      pod_ids: string[];
      /** Member Ids */
      member_ids: string[];
      /** Task Ids */
      task_ids: string[];
    };
    /** DirectorySearchResponse */
    DirectorySearchResponse: {
      /** Items */
      items: components["schemas"]["DirectoryUserResponse"][];
      /** Total */
      total: number;
    };
    /** DirectorySyncResponse */
    DirectorySyncResponse: {
      /** Tenant Id */
      tenant_id: string;
      /** Synced Count */
      synced_count: number;
      /** Deactivated Count */
      deactivated_count: number;
    };
    /** DirectoryUserResponse */
    DirectoryUserResponse: {
      /** External Id */
      external_id: string;
      /** Display Name */
      display_name: string;
      /** Email */
      email: string | null;
      /** Handle */
      handle: string | null;
      /** Avatar Url */
      avatar_url: string | null;
      /** Title */
      title: string | null;
      /** Is Active */
      is_active: boolean;
      /** Source */
      source: string;
      /** Metadata */
      metadata: {
        [key: string]: string | number | boolean | null;
      };
    };
    /**
     * EdgeKind
     * @enum {string}
     */
    EdgeKind: "contains" | "assigned_to" | "depends_on";
    /** EntityRefDto */
    EntityRefDto: {
      /** Tenant Id */
      tenant_id: string;
      kind: components["schemas"]["NodeKind"];
      /** Id */
      id: string;
    };
    /** FocusItemDto */
    FocusItemDto: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "task" | "blocker";
      /** Label */
      label: string;
      source: components["schemas"]["StatusSource"];
      source_ref: components["schemas"]["EntityRefDto"];
      /** Confidence */
      confidence: number | null;
      /** Deadline */
      deadline: string | null;
    };
    /** FocusResponse */
    FocusResponse: {
      /** Developer Id */
      developer_id: string;
      /** Developer Name */
      developer_name: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      status_source: components["schemas"]["StatusSource"];
      /** Status As Of */
      status_as_of: string | null;
      /** Summary */
      summary: string;
      /** Blockers */
      blockers: string[];
      /** Tasks */
      tasks: components["schemas"]["FocusTaskDto"][];
      /** Focus */
      focus: components["schemas"]["FocusItemDto"][];
    };
    /** FocusTaskDto */
    FocusTaskDto: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      rag: components["schemas"]["Rag"];
      source: components["schemas"]["StatusSource"];
      /** Confidence */
      confidence: number | null;
      /** Deadline */
      deadline: string | null;
    };
    /** GithubSyncDispatchRequest */
    GithubSyncDispatchRequest: {
      /** Tenant Id */
      tenant_id: string;
      /** Repo Name */
      repo_name: string;
      /** Observed At */
      observed_at?: string | null;
    };
    /** GraphEdgeDto */
    GraphEdgeDto: {
      /** From Node Id */
      from_node_id: string;
      /** To Node Id */
      to_node_id: string;
      kind: components["schemas"]["EdgeKind"];
      /** Valid From */
      valid_from: string | null;
      /** Valid To */
      valid_to: string | null;
    };
    /** GraphNodeDto */
    GraphNodeDto: {
      /** Id */
      id: string;
      kind: components["schemas"]["NodeKind"];
      /** Name */
      name: string;
      /** Metadata */
      metadata: {
        [key: string]: string | number | boolean | null;
      };
    };
    /** GraphTreeDto */
    GraphTreeDto: {
      root: components["schemas"]["GraphNodeDto"];
      /** Nodes */
      nodes: components["schemas"]["GraphNodeDto"][];
      /** Edges */
      edges: components["schemas"]["GraphEdgeDto"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
      /** Environment */
      environment: string;
      /** Tenant Id */
      tenant_id: string;
      /** Correlation Id */
      correlation_id: string;
    };
    /** HeatmapCellDto */
    HeatmapCellDto: {
      /** Row */
      row: string;
      /** Column */
      column: string;
      entity_ref: components["schemas"]["EntityRefDto"];
      rag: components["schemas"]["Rag"];
      source: components["schemas"]["StatusSource"];
      /** Why */
      why: string;
      source_ref: components["schemas"]["EntityRefDto"];
    };
    /** JiraSyncDispatchRequest */
    JiraSyncDispatchRequest: {
      /** Tenant Id */
      tenant_id: string;
      /** Project Key */
      project_key: string;
      /** Container Id */
      container_id?: string | null;
      /** Observed At */
      observed_at?: string | null;
    };
    /** MemberFromDirectoryRequest */
    MemberFromDirectoryRequest: {
      /** External Ids */
      external_ids: string[];
    };
    /** MemberTaskAssignmentRequest */
    MemberTaskAssignmentRequest: {
      /** Task Id */
      task_id: string;
    };
    /**
     * NodeKind
     * @enum {string}
     */
    NodeKind: "program" | "project" | "sprint" | "repo" | "pod" | "developer" | "task";
    /** PersonaTreeEdgeDto */
    PersonaTreeEdgeDto: {
      /** From Node Id */
      from_node_id: string;
      /** To Node Id */
      to_node_id: string;
      kind: components["schemas"]["EdgeKind"];
    };
    /** PersonaTreeNodeDto */
    PersonaTreeNodeDto: {
      /** Id */
      id: string;
      kind: components["schemas"]["NodeKind"];
      /** Name */
      name: string;
      rag: components["schemas"]["Rag"] | null;
      source: components["schemas"]["StatusSource"] | null;
      /** Confidence */
      confidence: number | null;
      /** Factors */
      factors: components["schemas"]["RollupFactorDto"][];
    };
    /** PodBlockersResponse */
    PodBlockersResponse: {
      /** Pod Id */
      pod_id: string;
      /** Pod Name */
      pod_name: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Blockers */
      blockers: components["schemas"]["BlockerDto"][];
    };
    /** PodCheckinsResponse */
    PodCheckinsResponse: {
      /** Pod Id */
      pod_id: string;
      /** Pod Name */
      pod_name: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Confirmed */
      confirmed: number;
      /** Stale */
      stale: number;
      /** Missing */
      missing: number;
      /** Developers */
      developers: components["schemas"]["CheckinDeveloperDto"][];
    };
    /** PodMemberLinkRequest */
    PodMemberLinkRequest: {
      /** Role */
      role: string;
    };
    /** PortfolioHeatmapResponse */
    PortfolioHeatmapResponse: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Rows */
      rows: string[];
      /** Columns */
      columns: string[];
      /** Cells */
      cells: components["schemas"]["HeatmapCellDto"][];
    };
    /** ProgramProjectLinkRequest */
    ProgramProjectLinkRequest: {
      /** Program Id */
      program_id: string;
    };
    /** ProgramTreeResponse */
    ProgramTreeResponse: {
      /** Root Id */
      root_id: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Nodes */
      nodes: components["schemas"]["PersonaTreeNodeDto"][];
      /** Edges */
      edges: components["schemas"]["PersonaTreeEdgeDto"][];
    };
    /** ProjectProgressResponse */
    ProjectProgressResponse: {
      /** Project Id */
      project_id: string;
      /** Project Name */
      project_name: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      rag: components["schemas"]["Rag"];
      source: components["schemas"]["StatusSource"];
      /** Confidence */
      confidence: number | null;
      /** Percent Complete */
      percent_complete: number;
      /** Total Tasks */
      total_tasks: number;
      /** Green Tasks */
      green_tasks: number;
      /** Amber Tasks */
      amber_tasks: number;
      /** Red Tasks */
      red_tasks: number;
      /** Unknown Tasks */
      unknown_tasks: number;
      /** Factors */
      factors: components["schemas"]["RollupFactorDto"][];
      /** Tasks */
      tasks: components["schemas"]["TaskProgressDto"][];
    };
    /**
     * Rag
     * @enum {string}
     */
    Rag: "green" | "amber" | "red" | "unknown";
    /** ReadyResponse */
    ReadyResponse: {
      /** Status */
      status: string;
      /** Dependencies */
      dependencies: {
        [key: string]: boolean;
      };
    };
    /** RollupFactorDto */
    RollupFactorDto: {
      /** Description */
      description: string;
      contributes: components["schemas"]["Rag"];
      source_ref: components["schemas"]["EntityRefDto"];
    };
    /**
     * StatusSource
     * @enum {string}
     */
    StatusSource: "confirmed" | "inferred" | "stale" | "unknown";
    /** TaskProgressDto */
    TaskProgressDto: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      rag: components["schemas"]["Rag"];
      source: components["schemas"]["StatusSource"];
      /** Confidence */
      confidence: number | null;
      /** Deadline */
      deadline: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WorkflowDispatchResponse */
    WorkflowDispatchResponse: {
      /** Workflow Id */
      workflow_id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  ready_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
    };
  };
  metrics_metrics_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  program_tree_graph_programs__program_id__tree_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GraphTreeDto"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dispatch_checkin_admin_workflows_checkin_dispatch_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckinDispatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDispatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dispatch_jira_sync_admin_workflows_sync_jira_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JiraSyncDispatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDispatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dispatch_github_sync_admin_workflows_sync_github_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GithubSyncDispatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDispatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dispatch_calendar_sync_admin_workflows_sync_calendar_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalendarSyncDispatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDispatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_config_programs_config_programs_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_config_program_config_programs_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigNodeCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_config_program_config_programs__program_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_config_program_config_programs__program_id__put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigNodeUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_config_program_config_programs__program_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_config_projects_config_projects_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_config_project_config_projects_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigNodeCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_config_project_config_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_config_project_config_projects__project_id__put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigNodeUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_config_project_config_projects__project_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_config_pods_config_pods_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_config_pod_config_pods_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigNodeCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_config_pod_config_pods__pod_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        pod_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_config_pod_config_pods__pod_id__put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        pod_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigNodeUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_config_pod_config_pods__pod_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        pod_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_config_members_config_members_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_config_member_config_members_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigNodeCreateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_config_directory_users_config_directory_users_get: {
    parameters: {
      query?: {
        query?: string;
        limit?: number;
        offset?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DirectorySearchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sync_config_directory_config_directory_sync_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DirectorySyncResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_config_members_from_directory_config_members_from_directory_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberFromDirectoryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_config_member_config_members__member_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_config_member_config_members__member_id__put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        member_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfigNodeUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigNodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_config_member_config_members__member_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  link_config_project_program_config_projects__project_id__program_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProgramProjectLinkRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigEdgeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  unlink_config_project_program_config_projects__project_id__program_delete: {
    parameters: {
      query?: {
        program_id?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  link_config_pod_project_config_pods__pod_id__projects__project_id__post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        pod_id: string;
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigEdgeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  unlink_config_pod_project_config_pods__pod_id__projects__project_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        pod_id: string;
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  link_config_pod_member_config_pods__pod_id__members__member_id__post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        pod_id: string;
        member_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PodMemberLinkRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigEdgeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  unlink_config_pod_member_config_pods__pod_id__members__member_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        pod_id: string;
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  assign_config_member_task_config_members__member_id__tasks_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        member_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberTaskAssignmentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigEdgeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  unassign_config_member_task_config_members__member_id__tasks_delete: {
    parameters: {
      query: {
        task_id: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_config_member_checkin_preference_config_members__member_id__checkin_preference_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckinPreferenceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_config_member_checkin_preference_config_members__member_id__checkin_preference_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        member_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckinPreferenceUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckinPreferenceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_config_checkin_preferences_config_checkin_preferences_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckinPreferenceResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_programs_programs_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DirectoryItemResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_projects_projects_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DirectoryItemResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_pods_pods_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DirectoryItemResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_checkin_preference_me_checkin_preference_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckinPreferenceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_checkin_preference_me_checkin_preference_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckinPreferenceUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckinPreferenceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_focus_me_focus_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FocusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pod_blockers_pods__pod_id__blockers_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        pod_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PodBlockersResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pod_checkins_pods__pod_id__checkins_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        pod_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PodCheckinsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  project_progress_projects__project_id__progress_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectProgressResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  program_tree_programs__program_id__tree_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramTreeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  portfolio_heatmap_portfolio_heatmap_get: {
    parameters: {
      query?: {
        as_of?: string;
        program_root_id?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioHeatmapResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  chat_simulator_status_test_chat_simulator_status_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatSimulatorStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  chat_simulator_messages_test_chat_simulator_messages_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatSimulatorMessagesResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  chat_simulator_reply_test_chat_simulator_messages__message_id__reply_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        message_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatSimulatorReplyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatSimulatorReplyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reset_chat_simulator_test_chat_simulator_state_delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  chat_webhook_webhooks_chat__provider__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatWebhookResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
