/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ready */
    get: operations["ready_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Metrics */
    get: operations["metrics_metrics_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/graph/programs/{program_id}/tree": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Program Tree */
    get: operations["program_tree_graph_programs__program_id__tree_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/workflows/checkin/dispatch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dispatch Checkin */
    post: operations["dispatch_checkin_admin_workflows_checkin_dispatch_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/workflows/sync/jira": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dispatch Jira Sync */
    post: operations["dispatch_jira_sync_admin_workflows_sync_jira_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/workflows/sync/github": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dispatch Github Sync */
    post: operations["dispatch_github_sync_admin_workflows_sync_github_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/workflows/sync/calendar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dispatch Calendar Sync */
    post: operations["dispatch_calendar_sync_admin_workflows_sync_calendar_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/checkin-preference": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Checkin Preference */
    get: operations["get_checkin_preference_me_checkin_preference_get"];
    /** Update Checkin Preference */
    put: operations["update_checkin_preference_me_checkin_preference_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/focus": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Focus */
    get: operations["my_focus_me_focus_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pods/{pod_id}/blockers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Pod Blockers */
    get: operations["pod_blockers_pods__pod_id__blockers_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pods/{pod_id}/checkins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Pod Checkins */
    get: operations["pod_checkins_pods__pod_id__checkins_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/projects/{project_id}/progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Project Progress */
    get: operations["project_progress_projects__project_id__progress_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/programs/{program_id}/tree": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Program Tree */
    get: operations["program_tree_programs__program_id__tree_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/portfolio/heatmap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Portfolio Heatmap */
    get: operations["portfolio_heatmap_portfolio_heatmap_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/webhooks/chat/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Chat Webhook */
    post: operations["chat_webhook_webhooks_chat__provider__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** BlockerDto */
    BlockerDto: {
      /** Id */
      id: string;
      /** Description */
      description: string;
      /** Age Days */
      age_days: number;
      /** Owner Id */
      owner_id: string;
      /** Owner Name */
      owner_name: string;
      source: components["schemas"]["StatusSource"];
      /**
       * Status As Of
       * Format: date
       */
      status_as_of: string;
      source_ref: components["schemas"]["EntityRefDto"];
    };
    /** CalendarSyncDispatchRequest */
    CalendarSyncDispatchRequest: {
      /** Tenant Id */
      tenant_id: string;
      /** User Id */
      user_id: string;
      /**
       * Start
       * Format: date
       */
      start: string;
      /**
       * End
       * Format: date
       */
      end: string;
      /** Display Name */
      display_name?: string | null;
      /** Observed At */
      observed_at?: string | null;
    };
    /** ChatWebhookResponse */
    ChatWebhookResponse: {
      /** Status */
      status: string;
      /** Message Id */
      message_id: string;
    };
    /** CheckinDeveloperDto */
    CheckinDeveloperDto: {
      /** Developer Id */
      developer_id: string;
      /** Developer Name */
      developer_name: string;
      /**
       * State
       * @enum {string}
       */
      state: "confirmed" | "stale" | "missing";
      source: components["schemas"]["StatusSource"];
      /** Status As Of */
      status_as_of: string | null;
      /** Summary */
      summary: string;
    };
    /** CheckinDispatchRequest */
    CheckinDispatchRequest: {
      /** Tenant Id */
      tenant_id: string;
      /** Developer Id */
      developer_id: string;
      /** Developer Name */
      developer_name?: string | null;
      /** Chat External Id */
      chat_external_id?: string | null;
      /** Checkin Date */
      checkin_date?: string | null;
    };
    /** CheckinPreferenceResponse */
    CheckinPreferenceResponse: {
      /** Developer Id */
      developer_id: string;
      /**
       * Local Time
       * Format: time
       */
      local_time: string;
      /** Timezone */
      timezone: string | null;
      /** Weekdays */
      weekdays: number[];
      /** Reply Wait Seconds */
      reply_wait_seconds: number;
      /** Final Reply Wait Seconds */
      final_reply_wait_seconds: number;
    };
    /** CheckinPreferenceUpdateRequest */
    CheckinPreferenceUpdateRequest: {
      /** Local Time */
      local_time?: string | null;
      /** Timezone */
      timezone?: string | null;
      /** Weekdays */
      weekdays?: number[] | null;
      /** Reply Wait Seconds */
      reply_wait_seconds?: number | null;
      /** Final Reply Wait Seconds */
      final_reply_wait_seconds?: number | null;
    };
    /**
     * EdgeKind
     * @enum {string}
     */
    EdgeKind: "contains" | "assigned_to" | "depends_on";
    /** EntityRefDto */
    EntityRefDto: {
      /** Tenant Id */
      tenant_id: string;
      kind: components["schemas"]["NodeKind"];
      /** Id */
      id: string;
    };
    /** FocusItemDto */
    FocusItemDto: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "task" | "blocker";
      /** Label */
      label: string;
      source: components["schemas"]["StatusSource"];
      source_ref: components["schemas"]["EntityRefDto"];
      /** Confidence */
      confidence: number | null;
      /** Deadline */
      deadline: string | null;
    };
    /** FocusResponse */
    FocusResponse: {
      /** Developer Id */
      developer_id: string;
      /** Developer Name */
      developer_name: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      status_source: components["schemas"]["StatusSource"];
      /** Status As Of */
      status_as_of: string | null;
      /** Summary */
      summary: string;
      /** Blockers */
      blockers: string[];
      /** Tasks */
      tasks: components["schemas"]["FocusTaskDto"][];
      /** Focus */
      focus: components["schemas"]["FocusItemDto"][];
    };
    /** FocusTaskDto */
    FocusTaskDto: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      rag: components["schemas"]["Rag"];
      source: components["schemas"]["StatusSource"];
      /** Confidence */
      confidence: number | null;
      /** Deadline */
      deadline: string | null;
    };
    /** GithubSyncDispatchRequest */
    GithubSyncDispatchRequest: {
      /** Tenant Id */
      tenant_id: string;
      /** Repo Name */
      repo_name: string;
      /** Observed At */
      observed_at?: string | null;
    };
    /** GraphEdgeDto */
    GraphEdgeDto: {
      /** From Node Id */
      from_node_id: string;
      /** To Node Id */
      to_node_id: string;
      kind: components["schemas"]["EdgeKind"];
      /** Valid From */
      valid_from: string | null;
      /** Valid To */
      valid_to: string | null;
    };
    /** GraphNodeDto */
    GraphNodeDto: {
      /** Id */
      id: string;
      kind: components["schemas"]["NodeKind"];
      /** Name */
      name: string;
      /** Metadata */
      metadata: {
        [key: string]: string | number | boolean | null;
      };
    };
    /** GraphTreeDto */
    GraphTreeDto: {
      root: components["schemas"]["GraphNodeDto"];
      /** Nodes */
      nodes: components["schemas"]["GraphNodeDto"][];
      /** Edges */
      edges: components["schemas"]["GraphEdgeDto"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
      /** Environment */
      environment: string;
      /** Tenant Id */
      tenant_id: string;
      /** Correlation Id */
      correlation_id: string;
    };
    /** HeatmapCellDto */
    HeatmapCellDto: {
      /** Row */
      row: string;
      /** Column */
      column: string;
      entity_ref: components["schemas"]["EntityRefDto"];
      rag: components["schemas"]["Rag"];
      source: components["schemas"]["StatusSource"];
      /** Why */
      why: string;
      source_ref: components["schemas"]["EntityRefDto"];
    };
    /** JiraSyncDispatchRequest */
    JiraSyncDispatchRequest: {
      /** Tenant Id */
      tenant_id: string;
      /** Project Key */
      project_key: string;
      /** Container Id */
      container_id?: string | null;
      /** Observed At */
      observed_at?: string | null;
    };
    /**
     * NodeKind
     * @enum {string}
     */
    NodeKind: "program" | "project" | "sprint" | "repo" | "pod" | "developer" | "task";
    /** PersonaTreeEdgeDto */
    PersonaTreeEdgeDto: {
      /** From Node Id */
      from_node_id: string;
      /** To Node Id */
      to_node_id: string;
      kind: components["schemas"]["EdgeKind"];
    };
    /** PersonaTreeNodeDto */
    PersonaTreeNodeDto: {
      /** Id */
      id: string;
      kind: components["schemas"]["NodeKind"];
      /** Name */
      name: string;
      rag: components["schemas"]["Rag"] | null;
      source: components["schemas"]["StatusSource"] | null;
      /** Confidence */
      confidence: number | null;
      /** Factors */
      factors: components["schemas"]["RollupFactorDto"][];
    };
    /** PodBlockersResponse */
    PodBlockersResponse: {
      /** Pod Id */
      pod_id: string;
      /** Pod Name */
      pod_name: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Blockers */
      blockers: components["schemas"]["BlockerDto"][];
    };
    /** PodCheckinsResponse */
    PodCheckinsResponse: {
      /** Pod Id */
      pod_id: string;
      /** Pod Name */
      pod_name: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Confirmed */
      confirmed: number;
      /** Stale */
      stale: number;
      /** Missing */
      missing: number;
      /** Developers */
      developers: components["schemas"]["CheckinDeveloperDto"][];
    };
    /** PortfolioHeatmapResponse */
    PortfolioHeatmapResponse: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Rows */
      rows: string[];
      /** Columns */
      columns: string[];
      /** Cells */
      cells: components["schemas"]["HeatmapCellDto"][];
    };
    /** ProgramTreeResponse */
    ProgramTreeResponse: {
      /** Root Id */
      root_id: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Nodes */
      nodes: components["schemas"]["PersonaTreeNodeDto"][];
      /** Edges */
      edges: components["schemas"]["PersonaTreeEdgeDto"][];
    };
    /** ProjectProgressResponse */
    ProjectProgressResponse: {
      /** Project Id */
      project_id: string;
      /** Project Name */
      project_name: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      rag: components["schemas"]["Rag"];
      source: components["schemas"]["StatusSource"];
      /** Confidence */
      confidence: number | null;
      /** Percent Complete */
      percent_complete: number;
      /** Total Tasks */
      total_tasks: number;
      /** Green Tasks */
      green_tasks: number;
      /** Amber Tasks */
      amber_tasks: number;
      /** Red Tasks */
      red_tasks: number;
      /** Unknown Tasks */
      unknown_tasks: number;
      /** Factors */
      factors: components["schemas"]["RollupFactorDto"][];
      /** Tasks */
      tasks: components["schemas"]["TaskProgressDto"][];
    };
    /**
     * Rag
     * @enum {string}
     */
    Rag: "green" | "amber" | "red" | "unknown";
    /** ReadyResponse */
    ReadyResponse: {
      /** Status */
      status: string;
      /** Dependencies */
      dependencies: {
        [key: string]: boolean;
      };
    };
    /** RollupFactorDto */
    RollupFactorDto: {
      /** Description */
      description: string;
      contributes: components["schemas"]["Rag"];
      source_ref: components["schemas"]["EntityRefDto"];
    };
    /**
     * StatusSource
     * @enum {string}
     */
    StatusSource: "confirmed" | "inferred" | "stale" | "unknown";
    /** TaskProgressDto */
    TaskProgressDto: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      rag: components["schemas"]["Rag"];
      source: components["schemas"]["StatusSource"];
      /** Confidence */
      confidence: number | null;
      /** Deadline */
      deadline: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** WorkflowDispatchResponse */
    WorkflowDispatchResponse: {
      /** Workflow Id */
      workflow_id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  ready_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
    };
  };
  metrics_metrics_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  program_tree_graph_programs__program_id__tree_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GraphTreeDto"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dispatch_checkin_admin_workflows_checkin_dispatch_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckinDispatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDispatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dispatch_jira_sync_admin_workflows_sync_jira_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JiraSyncDispatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDispatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dispatch_github_sync_admin_workflows_sync_github_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GithubSyncDispatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDispatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  dispatch_calendar_sync_admin_workflows_sync_calendar_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CalendarSyncDispatchRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkflowDispatchResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_checkin_preference_me_checkin_preference_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckinPreferenceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_checkin_preference_me_checkin_preference_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CheckinPreferenceUpdateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CheckinPreferenceResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  my_focus_me_focus_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FocusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pod_blockers_pods__pod_id__blockers_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        pod_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PodBlockersResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pod_checkins_pods__pod_id__checkins_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        pod_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PodCheckinsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  project_progress_projects__project_id__progress_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectProgressResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  program_tree_programs__program_id__tree_get: {
    parameters: {
      query?: {
        as_of?: string;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramTreeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  portfolio_heatmap_portfolio_heatmap_get: {
    parameters: {
      query?: {
        as_of?: string;
        program_root_id?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioHeatmapResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  chat_webhook_webhooks_chat__provider__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        provider: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChatWebhookResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
