import type { components } from "./generated";

export type NodeKind = components["schemas"]["NodeKind"];
export type EdgeKind = components["schemas"]["EdgeKind"];
export type HealthResponse = components["schemas"]["HealthResponse"];
export type ReadyResponse = components["schemas"]["ReadyResponse"];
export type GraphNodeDto = components["schemas"]["GraphNodeDto"];
export type GraphEdgeDto = components["schemas"]["GraphEdgeDto"];
export type GraphTreeDto = components["schemas"]["GraphTreeDto"];
export type ConfigNodeResponse = components["schemas"]["ConfigNodeResponse"];
export type ConfigNodeCreateRequest = components["schemas"]["ConfigNodeCreateRequest"];
export type ConfigNodeUpdateRequest = components["schemas"]["ConfigNodeUpdateRequest"];
export type ConfigEdgeResponse = components["schemas"]["ConfigEdgeResponse"];
export type DirectoryItemResponse = components["schemas"]["DirectoryItemResponse"];
export type DirectoryUserResponse = components["schemas"]["DirectoryUserResponse"];
export type DirectorySearchResponse = components["schemas"]["DirectorySearchResponse"];
export type DirectorySyncResponse = components["schemas"]["DirectorySyncResponse"];
export type MemberFromDirectoryRequest = components["schemas"]["MemberFromDirectoryRequest"];
export type StatusSource = components["schemas"]["StatusSource"];
export type Rag = components["schemas"]["Rag"];
export type EntityRefDto = components["schemas"]["EntityRefDto"];
export type RollupFactorDto = components["schemas"]["RollupFactorDto"];
export type FocusResponse = components["schemas"]["FocusResponse"];
export type CheckinPreferenceResponse = components["schemas"]["CheckinPreferenceResponse"];
export type CheckinPreferenceUpdateRequest =
  components["schemas"]["CheckinPreferenceUpdateRequest"];
export type PodMemberLinkRequest = components["schemas"]["PodMemberLinkRequest"];
export type ProgramProjectLinkRequest = components["schemas"]["ProgramProjectLinkRequest"];
export type MemberTaskAssignmentRequest = components["schemas"]["MemberTaskAssignmentRequest"];
export type PodBlockersResponse = components["schemas"]["PodBlockersResponse"];
export type PodCheckinsResponse = components["schemas"]["PodCheckinsResponse"];
export type ProjectProgressResponse = components["schemas"]["ProjectProgressResponse"];
export type ProgramTreeResponse = components["schemas"]["ProgramTreeResponse"];
export type PortfolioHeatmapResponse = components["schemas"]["PortfolioHeatmapResponse"];
